jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or your preferred distribution
          java-version: '17'     # Or your required JDK version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name = 'Make gradlew executable'
        run: chmod +x ./gradlew

      - name: Build with Gradle and Inject Secrets
        env:
          # Map GitHub Secrets to the exact property names used in build.gradle.kts
          # Pass the values *with quotes* to match the format expected by buildConfigField
          PEXELS_API_KEY: '"${{ secrets.PEXELS_API_KEY_SECRET }}"'
          OPENWEATHERMAP_API_KEY: '"${{ secrets.OPENWEATHERMAP_API_KEY_SECRET }}"'
        run: ./gradlew assembleRelease # Or assembleDebug, bundleRelease, etc.

      # Add steps for uploading artifacts, running tests etc.
